name: Build ebook

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r script/requirements.txt

    - name: Build epub
      run: |
        python script/make_epub.py

    - name: Download chmcmd
      run: |
        curl https://github.com/skywind3000/support/releases/download/1.0.0/chmcmd.zip -L > chmcmd.zip
        7z x chmcmd.zip
        copy chmcmd.exe .\build\
        ls

    - name: Build chm
      run: |
        $env:Path += ';.;.\HHW' 
        python script\make_chm.py

    - name: Clear up
      run: |
        Remove-Item -Path build\html -Recurse -Force
        Remove-Item -Path build\images -Recurse -Force
        Remove-Item -Path build\doc -Recurse -Force
        Remove-Item -Path build\*.exe -Recurse -Force
        Remove-Item -Path build\chm.hh* -Recurse -Force

    - name: Check output
      run: ls build
    
    - name: Upload result
      uses: actions/upload-artifact@v4.3.3
      with: 
        # name: # optional, default is artifact 
        path: build 
  

  release:
    # if: startsWith(github.ref, 'refs/tags/')

    runs-on: windows-latest

    needs: build

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: List downloaded files
        run: ls build


